services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Security\EventListener\RequiredFieldsListener:
    tags:
      - { name: kernel.event_listener, event: kernel.controller }

  Security\EventListener\AuthenticatedListener:
    tags:
      - { name: kernel.event_listener, event: kernel.controller, priority: 998 }

  Security\EventListener\RoleGuardListener:
    tags:
      - { name: kernel.event_listener, event: kernel.controller, priority: 997 }

  Security\EventListener\JwtRequestListener:
    tags:
      - { name: "kernel.event_listener", event: "kernel.request",method: "onKernelRequest", priority: 999 }

  Security\Service\JwtService:
    arguments:
      $privateKey: '%private_key%'